version: "3.8"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # Enable polling so that file changes are detected reliably
      - CHOKIDAR_USEPOLLING=true
