version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: ai-assistant-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/ai-assistant
      - JWT_SECRET=your_jwt_secret_here
      - GOOGLE_AI_API_KEY=your_google_ai_api_key_here
      - AI_INSTRUCTIONS=Your system instructions for the AI assistant
    depends_on:
      - mongo

volumes:
  mongo-data:
